# Quick Windows setup for backend CORS and dev run
# Usage:
#   PowerShell (Run):  .\setup.ps1

param(
  [string]$Port = "3001",
  [string]$CorsOrigins = "http://localhost:5173,https://crisiscore-systems.github.io"
)

$envPath = Join-Path $PSScriptRoot ".env"

Write-Host "Generating .env at $envPath" -ForegroundColor Cyan

$content = @"
# Generated by setup.ps1
NODE_ENV=development
PORT=$Port

# CORS: comma-separated list of allowed origins
CORS_ORIGIN=$CorsOrigins

# JWT (dev default)
JWT_SECRET=dev-secret-change-me

# Postgres (adjust as needed)
# Use 127.0.0.1 to avoid IPv6 (::1) auth differences on Windows
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=neural_entrainment
DB_USER=postgres
DB_PASSWORD=postgres

# Redis (optional for dev)
REDIS_HOST=localhost
REDIS_PORT=6379
"@

Set-Content -Path $envPath -Value $content -Encoding UTF8

Write-Host "[OK] .env created with CORS_ORIGIN=$CorsOrigins" -ForegroundColor Green
Write-Host "To start the backend in dev: cd $PSScriptRoot; npm install; npm run dev" -ForegroundColor Yellow
